<?php

namespace TurismoBundle\Repository;

/**
 * TurismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurismoRepository extends \Doctrine\ORM\EntityRepository
{
}
